{% set name = "jlab-enhanced-launcher" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cace965ba7aeeff274eca382ac143c6935400041da39d1ec66d9223574e1d378

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs >=14.0.0
  host:
    - python >=3.7
    - pip
    - jupyterlab >=3.1.0
    - jupyter-packaging >=0.10.0,<2.0.0
  run:
    - python >=3.7

test:
  requires:
    - pip
    - jupyterlab >=3.1.0
  commands:
    - pip check
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/launcher.*OK"
    - python -m jupyterlab.browser_check --no-browser-test

about:
  home: https://github.com/fcollonval/jlab-enhanced-launcher
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A enhanced launcher for JupyterLab.
  dev_url: https://github.com/fcollonval/jlab-enhanced-launcher

extra:
  recipe-maintainers:
    - fcollonval
