{% set name = "jlab-enhanced-launcher" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cace965ba7aeeff274eca382ac143c6935400041da39d1ec66d9223574e1d378

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/launcher.*OK"

about:
  home: https://github.com/fcollonval/jlab-enhanced-launcher
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A enhanced launcher for JupyterLab.
  dev_url: https://github.com/fcollonval/jlab-enhanced-launcher

extra:
  recipe-maintainers:
    - fcollonval
